sudo: true
dist: trusty
cache:
  directories:
    - "$HOME/.m2"
language: java
before_install:
  - rm ~/.m2/settings.xml
  - cd ~ && git clone https://github.com/OpenBfS/dokpool-javaclient.git && cd dokpool-javaclient && mvn clean install && cd -
script:
  - mvn clean compile package install
notifications:
  email:
    on_success: never
    on_failure: never
jdk:
- oraclejdk7
- openjdk7
- oraclejdk8
- openjdk8

